export type Country = {
  code: string;
  name: string;
  capital: string;
};

export const COUNTRIES: Country[] = [
  { name: 'Afghanistan', code: 'AF', capital: 'Kabul' },
  { name: 'Albania', code: 'AL', capital: 'Tirana' },
  { name: 'Algeria', code: 'DZ', capital: 'Algiers' },
  { name: 'Andorra', code: 'AD', capital: 'Andorra la Vella' },
  { name: 'Angola', code: 'AO', capital: 'Luanda' },
  { name: 'Argentina', code: 'AR', capital: 'Buenos Aires' },
  { name: 'Australia', code: 'AU', capital: 'Canberra' },
  { name: 'Austria', code: 'AT', capital: 'Vienna' },
  { name: 'Bangladesh', code: 'BD', capital: 'Dhaka' },
  { name: 'Belarus', code: 'BY', capital: 'Minsk' },
  { name: 'Belgium', code: 'BE', capital: 'Brussels' },
  { name: 'Bolivia', code: 'BO', capital: 'Sucre' },
  { name: 'Brazil', code: 'BR', capital: 'Brasília' },
  { name: 'Bulgaria', code: 'BG', capital: 'Sofia' },
  { name: 'Cambodia', code: 'KH', capital: 'Phnom Penh' },
  { name: 'Canada', code: 'CA', capital: 'Ottawa' },
  { name: 'Chile', code: 'CL', capital: 'Santiago' },
  { name: 'China', code: 'CN', capital: 'Beijing' },
  { name: 'Colombia', code: 'CO', capital: 'Bogotá' },
  { name: 'Costa Rica', code: 'CR', capital: 'San José' },
  { name: 'Croatia', code: 'HR', capital: 'Zagreb' },
  { name: 'Cuba', code: 'CU', capital: 'Havana' },
  { name: 'Czech Republic', code: 'CZ', capital: 'Prague' },
  { name: 'Denmark', code: 'DK', capital: 'Copenhagen' },
  { name: 'Ecuador', code: 'EC', capital: 'Quito' },
  { name: 'Egypt', code: 'EG', capital: 'Cairo' },
  { name: 'Estonia', code: 'EE', capital: 'Tallinn' },
  { name: 'Ethiopia', code: 'ET', capital: 'Addis Ababa' },
  { name: 'Finland', code: 'FI', capital: 'Helsinki' },
  { name: 'France', code: 'FR', capital: 'Paris' },
  { name: 'Germany', code: 'DE', capital: 'Berlin' },
  { name: 'Greece', code: 'GR', capital: 'Athens' },
  { name: 'Hungary', code: 'HU', capital: 'Budapest' },
  { name: 'Iceland', code: 'IS', capital: 'Reykjavik' },
  { name: 'India', code: 'IN', capital: 'New Delhi' },
  { name: 'Indonesia', code: 'ID', capital: 'Jakarta' },
  { name: 'Iran', code: 'IR', capital: 'Tehran' },
  { name: 'Iraq', code: 'IQ', capital: 'Baghdad' },
  { name: 'Ireland', code: 'IE', capital: 'Dublin' },
  { name: 'Israel', code: 'IL', capital: 'Jerusalem' },
  { name: 'Italy', code: 'IT', capital: 'Rome' },
  { name: 'Jamaica', code: 'JM', capital: 'Kingston' },
  { name: 'Japan', code: 'JP', capital: 'Tokyo' },
  { name: 'Kenya', code: 'KE', capital: 'Nairobi' },
  { name: 'Madagascar', code: 'MG', capital: 'Antananarivo' },
  { name: 'Malaysia', code: 'MY', capital: 'Kuala Lumpur' },
  { name: 'Mexico', code: 'MX', capital: 'Mexico City' },
  { name: 'Mongolia', code: 'MN', capital: 'Ulaanbaatar' },
  { name: 'Morocco', code: 'MA', capital: 'Rabat' },
  { name: 'Nepal', code: 'NP', capital: 'Kathmandu' },
  { name: 'Netherlands', code: 'NL', capital: 'Amsterdam' },
  { name: 'New Zealand', code: 'NZ', capital: 'Wellington' },
  { name: 'Nigeria', code: 'NG', capital: 'Abuja' },
  { name: 'North Korea', code: 'KP', capital: 'Pyongyang' },
  { name: 'Norway', code: 'NO', capital: 'Oslo' },
  { name: 'Pakistan', code: 'PK', capital: 'Islamabad' },
  { name: 'Peru', code: 'PE', capital: 'Lima' },
  { name: 'Philippines', code: 'PH', capital: 'Manila' },
  { name: 'Poland', code: 'PL', capital: 'Warsaw' },
  { name: 'Portugal', code: 'PT', capital: 'Lisbon' },
  { name: 'Qatar', code: 'QA', capital: 'Doha' },
  { name: 'Romania', code: 'RO', capital: 'Bucharest' },
  { name: 'Russia', code: 'RU', capital: 'Moscow' },
  { name: 'Saudi Arabia', code: 'SA', capital: 'Riyadh' },
  { name: 'Serbia', code: 'RS', capital: 'Belgrade' },
  { name: 'Singapore', code: 'SG', capital: 'Singapore' },
  { name: 'South Africa', code: 'ZA', capital: 'Pretoria' },
  { name: 'South Korea', code: 'KR', capital: 'Seoul' },
  { name: 'Spain', code: 'ES', capital: 'Madrid' },
  { name: 'Sweden', code: 'SE', capital: 'Stockholm' },
  { name: 'Switzerland', code: 'CH', capital: 'Bern' },
  { name: 'Syria', code: 'SY', capital: 'Damascus' },
  { name: 'Thailand', code: 'TH', capital: 'Bangkok' },
  { name: 'Turkey', code: 'TR', capital: 'Ankara' },
  { name: 'Ukraine', code: 'UA', capital: 'Kyiv' },
  { name: 'United Arab Emirates', code: 'AE', capital: 'Abu Dhabi' },
  { name: 'United Kingdom', code: 'GB', capital: 'London' },
  { name: 'United States', code: 'US', capital: 'Washington, D.C.' },
  { name: 'Uruguay', code: 'UY', capital: 'Montevideo' },
  { name: 'Uzbekistan', code: 'UZ', capital: 'Tashkent' },
  { name: 'Venezuela', code: 'VE', capital: 'Caracas' },
  { name: 'Vietnam', code: 'VN', capital: 'Hanoi' },
];
